name: Images / Home Assistant

on:
  push:
    branches:
      - master
    paths:
      - images/home-assistant/**
      - Makefile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: make images/radicale/build -B
      - run: make images/radicale/push
        env:
          REGISTRY: docker.io
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
          USER: ${{ secrets.DOCKER_USER }}
