name: Images / StaticHugo

on:
  push:
    branches:
      - master
    paths:
      - images/static-hugo/**
      - Makefile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: make images/static-hugo/build -B
      - run: make images/static-hugo/push
        env:
          REGISTRY: docker.io
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
          USER: ${{ secrets.DOCKER_USER }}
