name: Images / Home Assistant

on:
  push:
    branches:
      - master
    paths:
      - images/home-assistant/**
      - Makefile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: make images/home-assistant -B
